# Asked GPT to find mapped or most-similar ones. value is in the format of [sonar_lang_id, mlsuperb2_fullname, sonar_fullname]
mapping_no_empty={
  'grn': ['grn_Latn', 'Guaraní', 'Guarani'],
  'yor': ['yor_Latn', 'Yoruba', 'Yoruba'],
  'mon': ['khk_Cyrl', 'Mongolian', 'Halh Mongolian'],
  'azz': ['spa_Latn', 'Highland Puebla Nahuatl', 'Spanish'],
  'bos': ['bos_Latn', 'Bosnian', 'Bosnian'],
  'lga': ['tpi_Latn', 'Lungga', 'Tok Pisin'],
  'kin': ['kin_Latn', 'Kinyarwanda', 'Kinyarwanda'],
  'msa': ['zsm_Latn', 'Malay', 'Standard Malay'],
  'ven': ['sna_Latn', 'Venda', 'Shona'],
  'ukr': ['ukr_Cyrl', 'Ukrainian', 'Ukrainian'],
  'fil': ['tgl_Latn', 'Filipino', 'Tagalog'],
  'glg': ['glg_Latn', 'Galician', 'Galician'],
  'cym': ['cym_Latn', 'Welsh', 'Welsh'],
  'org_jpn': ['jpn_Jpan', 'Japanese (original script)', 'Japanese'],
  'tgk': ['tgk_Cyrl', 'Tajik', 'Tajik'],
  'mrj': ['rus_Cyrl', 'Hill Mari (Western Mari)', 'Russian'],
  'tso': ['tso_Latn', 'Tsonga', 'Tsonga'],
  'tsn': ['tsn_Latn', 'Tswana', 'Tswana'],
  'tok': ['epo_Latn', 'Toki Pona', 'Esperanto'],
  'zul': ['zul_Latn', 'Zulu', 'Zulu'],
  'epo': ['epo_Latn', 'Esperanto', 'Esperanto'],
  'afr': ['afr_Latn', 'Afrikaans', 'Afrikaans'],
  'kmr': ['kmr_Latn', 'Northern Kurdish (Kurmanji)', 'Northern Kurdish'],
  'oci': ['oci_Latn', 'Occitan', 'Occitan'],
  'ast': ['ast_Latn', 'Asturian', 'Asturian'],
  'hye': ['hye_Armn', 'Armenian', 'Armenian'],
  'ita': ['ita_Latn', 'Italian', 'Italian'],
  'orm': ['gaz_Latn', 'Oromo', 'West Central Oromo'],
  'ssw': ['ssw_Latn', 'Swati (siSwati)', 'Swati'],
  'lin': ['lin_Latn', 'Lingala', 'Lingala'],
  'som': ['som_Latn', 'Somali', 'Somali'],
  'dan': ['dan_Latn', 'Danish', 'Danish'],
  'fin': ['fin_Latn', 'Finnish', 'Finnish'],
  'nep': ['npi_Deva', 'Nepali', 'Nepali'],
  'umb': ['umb_Latn', 'Umbundu', 'Umbundu'],
  'sun': ['sun_Latn', 'Sundanese', 'Sundanese'],
  'aze': ['azj_Latn', 'Azerbaijani', 'North Azerbaijani'],
  'luo': ['luo_Latn', 'Luo', 'Luo'],
  'hrv': ['hrv_Latn', 'Croatian', 'Croatian'],
  'isl': ['isl_Latn', 'Icelandic', 'Icelandic'],
  'mlt': ['mlt_Latn', 'Maltese', 'Maltese'],
  'ory': ['ory_Orya', 'Odia (Oriya)', 'Odia'],
  'amh': ['amh_Ethi', 'Amharic', 'Amharic'],
  'fas': ['pes_Arab', 'Persian (Farsi)', 'Western Persian'],
  'kab': ['kab_Latn', 'Kabyle', 'Kabyle'],
  'snd': ['snd_Arab', 'Sindhi', 'Sindhi'],
  'tur': ['tur_Latn', 'Turkish', 'Turkish'],
  'swe': ['swe_Latn', 'Swedish', 'Swedish'],
  'kaz': ['kaz_Cyrl', 'Kazakh', 'Kazakh'],
  'nob': ['nob_Latn', 'Norwegian Bokmål (generic “Norwegian” when unspecified)', 'Norwegian Bokmål'],
  'uig': ['uig_Arab', 'Uyghur', 'Uyghur'],
  'jpn': ['jpn_Jpan', 'Japanese', 'Japanese'],
  'mya': ['mya_Mymr', 'Burmese', 'Burmese'],
  'sot': ['sot_Latn', 'Southern Sotho', 'Southern Sotho'],
  'nan': ['zho_Hant', 'Min Nan Chinese (Hokkien)', 'Chinese (Traditional)'],
  'kor': ['kor_Hang', 'Korean', 'Korean'],
  'slk': ['slk_Latn', 'Slovak', 'Slovak'],
  'por': ['por_Latn', 'Portuguese', 'Portuguese'],
  'cat': ['cat_Latn', 'Catalan', 'Catalan'],
  'yue': ['yue_Hant', 'Yue Chinese (Cantonese)', 'Yue Chinese'],
  'wol': ['wol_Latn', 'Wolof', 'Wolof'],
  'kan': ['kan_Knda', 'Kannada', 'Kannada'],
  'est': ['est_Latn', 'Estonian', 'Estonian'],
  'pus': ['pbt_Arab', 'Pashto', 'Southern Pashto'],
  'ibo': ['ibo_Latn', 'Igbo', 'Igbo'],
  'cnh': ['mya_Mymr', 'Hakha Chin', 'Burmese'],
  'tel': ['tel_Telu', 'Telugu', 'Telugu'],
  'hsb': ['pol_Latn', 'Upper Sorbian', 'Polish'],
  'kir': ['kir_Cyrl', 'Kyrgyz', 'Kyrgyz'],
  'guj': ['guj_Gujr', 'Gujarati', 'Gujarati'],
  'eng': ['eng_Latn', 'English', 'English'],
  'xty': ['spa_Latn', 'Yoloxochitl Mixtec', 'Spanish'],
  'swa': ['swh_Latn', 'Swahili', 'Swahili'],
  'mkd': ['mkd_Cyrl', 'Macedonian', 'Macedonian'],
  'sna': ['sna_Latn', 'Shona', 'Shona'],
  'gle': ['gle_Latn', 'Irish', 'Irish'],
  'ckb': ['ckb_Arab', 'Central Kurdish (Sorani)', 'Central Kurdish'],
  'kea': ['kea_Latn', 'Kabuverdianu (Cape Verdean Creole)', 'Kabuverdianu'],
  'tha': ['tha_Thai', 'Thai', 'Thai'],
  'spa': ['spa_Latn', 'Spanish', 'Spanish'],
  'khm': ['khm_Khmr', 'Khmer', 'Khmer'],
  'chv': ['tat_Cyrl', 'Chuvash', 'Tatar'],
  'ind': ['ind_Latn', 'Indonesian', 'Indonesian'],
  'ron': ['ron_Latn', 'Romanian', 'Romanian'],
  'hun': ['hun_Latn', 'Hungarian', 'Hungarian'],
  'jav': ['jav_Latn', 'Javanese', 'Javanese'],
  'bul': ['bul_Cyrl', 'Bulgarian', 'Bulgarian'],
  'ara': ['arb_Arab', 'Arabic', 'Modern Standard Arabic'],
  'ina': ['ita_Latn', 'Interlingua', 'Italian'],
  'mri': ['mri_Latn', 'Māori', 'Maori'],
  'xho': ['xho_Latn', 'Xhosa', 'Xhosa'],
  'skr': ['urd_Arab', 'Saraiki', 'Urdu'],
  'kam': ['kam_Latn', 'Kamba', 'Kamba'],
  'slv': ['slv_Latn', 'Slovenian', 'Slovenian'],
  'tat': ['tat_Cyrl', 'Tatar', 'Tatar'],
  'nbl': ['zul_Latn', 'South Ndebele', 'Zulu'],
  'ori': ['ory_Orya', 'Odia (Oriya)', 'Odia'],
  'ces': ['ces_Latn', 'Czech', 'Czech'],
  'sah': ['rus_Cyrl', 'Sakha (Yakut)', 'Russian'],
  'lao': ['lao_Laoo', 'Lao', 'Lao'],
  'vie': ['vie_Latn', 'Vietnamese', 'Vietnamese'],
  'frr': ['deu_Latn', 'North Frisian', 'German'],
  'uzb': ['uzn_Latn', 'Uzbek', 'Northern Uzbek'],
  'bel': ['bel_Cyrl', 'Belarusian', 'Belarusian'],
  'mhr': ['rus_Cyrl', 'Meadow Mari (Eastern Mari)', 'Russian'],
  'nno': ['nno_Latn', 'Norwegian Nynorsk', 'Norwegian Nynorsk'],
  'ben': ['ben_Beng', 'Bengali', 'Bengali'],
  'asm': ['asm_Beng', 'Assamese', 'Assamese'],
  'bak': ['bak_Cyrl', 'Bashkir', 'Bashkir'],
  'ell': ['ell_Grek', 'Greek', 'Greek'],
  'ceb': ['ceb_Latn', 'Cebuano', 'Cebuano'],
  'heb': ['heb_Hebr', 'Hebrew', 'Hebrew'],
  'pan': ['pan_Guru', 'Punjabi (Gurmukhi)', 'Eastern Panjabi'],
  'nor': ['nob_Latn', 'Norwegian (unspecified)', 'Norwegian Bokmål'],
  'myv': ['rus_Cyrl', 'Erzya', 'Russian'],
  'ful': ['fuv_Latn', 'Fulah (Fula, Fulfulde)', 'Nigerian Fulfulde'],
  'div': ['sin_Sinh', 'Dhivehi (Maldivian)', 'Sinhala'],
  'srp': ['srp_Cyrl', 'Serbian', 'Serbian'],
  'tam': ['tam_Taml', 'Tamil', 'Tamil'],
  'eus': ['eus_Latn', 'Basque', 'Basque'],
  'nld': ['nld_Latn', 'Dutch', 'Dutch'],
  'lit': ['lit_Latn', 'Lithuanian', 'Lithuanian'],
  'urd': ['urd_Arab', 'Urdu', 'Urdu'],
  'tos': ['als_Latn', 'Tosk Albanian', 'Tosk Albanian'],
  'mal': ['mal_Mlym', 'Malayalam', 'Malayalam'],
  'lug': ['lug_Latn', 'Luganda (Ganda)', 'Ganda'],
  'pol': ['pol_Latn', 'Polish', 'Polish'],
  'bas': ['fra_Latn', 'Basaa (Basa)', 'French'],
  'bre': ['cym_Latn', 'Breton', 'Welsh'],
  'fra': ['fra_Latn', 'French', 'French'],
  'rus': ['rus_Cyrl', 'Russian', 'Russian'],
  'cmn': ['zho_Hans', 'Mandarin Chinese', 'Chinese (Simplified)'],
  'ltz': ['ltz_Latn', 'Luxembourgish', 'Luxembourgish'],
  'lav': ['lvs_Latn', 'Latvian', 'Standard Latvian'],
  'sin': ['sin_Sinh', 'Sinhala', 'Sinhala'],
  'deu': ['deu_Latn', 'German', 'German'],
  'hin': ['hin_Deva', 'Hindi', 'Hindi'],
  'abk': ['rus_Cyrl', 'Abkhaz', 'Russian'],
  'kat': ['kat_Geor', 'Georgian', 'Georgian'],
  'nso': ['nso_Latn', 'Northern Sotho', 'Northern Sotho'],
  'nya': ['nya_Latn', 'Nyanja (Chichewa)', 'Nyanja'],
  'mar': ['mar_Deva', 'Marathi', 'Marathi'],
  'hau': ['hau_Latn', 'Hausa', 'Hausa']
}

mapping_with_empty={"grn": ["grn_Latn", "Guarani", "Guarani"],
    "yor": ["yor_Latn", "Yoruba", "Yoruba"],
    "mon": ["khk_Cyrl", "Mongolian", "Halh Mongolian"],
    "azz": ["", "Highland Puebla Nahuatl", ""],  # not in list2
    "bos": ["bos_Latn", "Bosnian", "Bosnian"],
    "lga": ["", "Luganda?", ""],  # unclear, not in list2
    "kin": ["kin_Latn", "Kinyarwanda", "Kinyarwanda"],
    "msa": ["zsm_Latn", "Malay", "Standard Malay"],
    "ven": ["vec_Latn", "Venda", "Venetian"],  # closest is Venetian, not Venda
    "ukr": ["ukr_Cyrl", "Ukrainian", "Ukrainian"],
    "fil": ["tgl_Latn", "Filipino", "Tagalog"],
    "glg": ["glg_Latn", "Galician", "Galician"],
    "cym": ["cym_Latn", "Welsh", "Welsh"],
    "org_jpn": ["jpn_Jpan", "Japanese (original)", "Japanese"],
    "tgk": ["tgk_Cyrl", "Tajik", "Tajik"],
    "mrj": ["mhr_Latn", "Hill Mari", "Eastern Mari (mhr not in list2)"],  # approx
    "tso": ["tso_Latn", "Tsonga", "Tsonga"],
    "tsn": ["tsn_Latn", "Tswana", "Tswana"],
    "tok": ["tpi_Latn", "Toki Pona", "Tok Pisin"],  # not exact but closest
    "zul": ["zul_Latn", "Zulu", "Zulu"],
    "epo": ["epo_Latn", "Esperanto", "Esperanto"],
    "afr": ["afr_Latn", "Afrikaans", "Afrikaans"],
    "kmr": ["kmr_Latn", "Northern Kurdish", "Northern Kurdish"],
    "oci": ["oci_Latn", "Occitan", "Occitan"],
    "ast": ["ast_Latn", "Asturian", "Asturian"],
    "hye": ["hye_Armn", "Armenian", "Armenian"],
    "ita": ["ita_Latn", "Italian", "Italian"],
    "orm": ["gaz_Latn", "Oromo", "West Central Oromo"],
    "ssw": ["ssw_Latn", "Swati", "Swati"],
    "lin": ["lin_Latn", "Lingala", "Lingala"],
    "som": ["som_Latn", "Somali", "Somali"],
    "dan": ["dan_Latn", "Danish", "Danish"],
    "fin": ["fin_Latn", "Finnish", "Finnish"],
    "nep": ["npi_Deva", "Nepali", "Nepali"],
    "umb": ["umb_Latn", "Umbundu", "Umbundu"],
    "sun": ["sun_Latn", "Sundanese", "Sundanese"],
    "aze": ["azj_Latn", "Azerbaijani", "North Azerbaijani"],
    "luo": ["luo_Latn", "Luo", "Luo"],
    "hrv": ["hrv_Latn", "Croatian", "Croatian"],
    "isl": ["isl_Latn", "Icelandic", "Icelandic"],
    "mlt": ["mlt_Latn", "Maltese", "Maltese"],
    "ory": ["ory_Orya", "Odia", "Odia"],
    "amh": ["amh_Ethi", "Amharic", "Amharic"],
    "fas": ["pes_Arab", "Persian", "Western Persian"],
    "kab": ["kab_Latn", "Kabyle", "Kabyle"],
    "snd": ["snd_Arab", "Sindhi", "Sindhi"],
    "tur": ["tur_Latn", "Turkish", "Turkish"],
    "swe": ["swe_Latn", "Swedish", "Swedish"],
    "kaz": ["kaz_Cyrl", "Kazakh", "Kazakh"],
    "nob": ["nob_Latn", "Norwegian Bokmål", "Norwegian Bokmål"],
    "uig": ["uig_Arab", "Uyghur", "Uyghur"],
    "jpn": ["jpn_Jpan", "Japanese", "Japanese"],
    "mya": ["mya_Mymr", "Burmese", "Burmese"],
    "sot": ["sot_Latn", "Southern Sotho", "Southern Sotho"],
    "nan": ["zho_Hant", "Southern Min", "Chinese (Traditional)"],  # approx
    "kor": ["kor_Hang", "Korean", "Korean"],
    "slk": ["slk_Latn", "Slovak", "Slovak"],
    "por": ["por_Latn", "Portuguese", "Portuguese"],
    "cat": ["cat_Latn", "Catalan", "Catalan"],
    "yue": ["yue_Hant", "Cantonese", "Yue Chinese"],
    "wol": ["wol_Latn", "Wolof", "Wolof"],
    "kan": ["kan_Knda", "Kannada", "Kannada"],
    "est": ["est_Latn", "Estonian", "Estonian"],
    "pus": ["pbt_Arab", "Pashto", "Southern Pashto"],  # approx
    "ibo": ["ibo_Latn", "Igbo", "Igbo"],
    "cnh": ["", "Hakha Chin", ""],  # not in list2
    "tel": ["tel_Telu", "Telugu", "Telugu"],
    "hsb": ["", "Upper Sorbian", ""],  # not in list2
    "kir": ["kir_Cyrl", "Kyrgyz", "Kyrgyz"],
    "guj": ["guj_Gujr", "Gujarati", "Gujarati"],
    "eng": ["eng_Latn", "English", "English"],
    "xty": ["", "Yoloxóchitl Mixtec", ""],  # not in list2
    "swa": ["swh_Latn", "Swahili", "Swahili"],
    "mkd": ["mkd_Cyrl", "Macedonian", "Macedonian"],
    "sna": ["sna_Latn", "Shona", "Shona"],
    "gle": ["gle_Latn", "Irish", "Irish"],
    "ckb": ["ckb_Arab", "Central Kurdish", "Central Kurdish"],
    "kea": ["kea_Latn", "Kabuverdianu", "Kabuverdianu"],
    "tha": ["tha_Thai", "Thai", "Thai"],
    "spa": ["spa_Latn", "Spanish", "Spanish"],
    "khm": ["khm_Khmr", "Khmer", "Khmer"],
    "chv": ["", "Chuvash", ""],  # not in list2
    "ind": ["ind_Latn", "Indonesian", "Indonesian"],
    "ron": ["ron_Latn", "Romanian", "Romanian"],
    "hun": ["hun_Latn", "Hungarian", "Hungarian"],
    "jav": ["jav_Latn", "Javanese", "Javanese"],
    "bul": ["bul_Cyrl", "Bulgarian", "Bulgarian"],
    "ara": ["arb_Arab", "Arabic", "Modern Standard Arabic"],
    "ina": ["", "Interlingua", ""],  # not in list2
    "mri": ["mri_Latn", "Maori", "Maori"],
    "xho": ["xho_Latn", "Xhosa", "Xhosa"],
    "skr": ["", "Saraiki", ""],  # not in list2
    "kam": ["kam_Latn", "Kamba", "Kamba"],
    "slv": ["slv_Latn", "Slovenian", "Slovenian"],
    "tat": ["tat_Cyrl", "Tatar", "Tatar"],
    "nbl": ["", "Southern Ndebele", ""],  # not in list2
    "ori": ["ory_Orya", "Oriya", "Odia"],
    "ces": ["ces_Latn", "Czech", "Czech"],
    "sah": ["", "Sakha", ""],  # not in list2
    "lao": ["lao_Laoo", "Lao", "Lao"],
    "vie": ["vie_Latn", "Vietnamese", "Vietnamese"],
    "frr": ["", "Northern Frisian", ""],  # not in list2
    "uzb": ["uzn_Latn", "Uzbek", "Northern Uzbek"],
    "bel": ["bel_Cyrl", "Belarusian", "Belarusian"],
    "mhr": ["", "Meadow Mari", ""],  # not in list2
    "nno": ["nno_Latn", "Norwegian Nynorsk", "Norwegian Nynorsk"],
    "ben": ["ben_Beng", "Bengali", "Bengali"],
    "asm": ["asm_Beng", "Assamese", "Assamese"],
    "bak": ["bak_Cyrl", "Bashkir", "Bashkir"],
    "ell": ["ell_Grek", "Greek", "Greek"],
    "ceb": ["ceb_Latn", "Cebuano", "Cebuano"],
    "heb": ["heb_Hebr", "Hebrew", "Hebrew"],
    "pan": ["pan_Guru", "Punjabi", "Eastern Panjabi"],
    "nor": ["nob_Latn", "Norwegian", "Norwegian Bokmål"],
    "myv": ["", "Erzya", ""],  # not in list2
    "ful": ["fuv_Latn", "Fula", "Nigerian Fulfulde"],
    "div": ["", "Dhivehi", ""],  # not in list2
    "srp": ["srp_Cyrl", "Serbian", "Serbian"],
    "tam": ["tam_Taml", "Tamil", "Tamil"],
    "eus": ["eus_Latn", "Basque", "Basque"],
    "nld": ["nld_Latn", "Dutch", "Dutch"],
    "lit": ["lit_Latn", "Lithuanian", "Lithuanian"],
    "urd": ["urd_Arab", "Urdu", "Urdu"],
    "tos": ["", "Tonga (Zambia)?", ""],  # not in list2
    "mal": ["mal_Mlym", "Malayalam", "Malayalam"],
    "lug": ["lug_Latn", "Luganda", "Ganda"],
    "pol": ["pol_Latn", "Polish", "Polish"],
    "bas": ["", "Basaa", ""],  # not in list2
    "bre": ["", "Breton", ""],  # not in list2
    "fra": ["fra_Latn", "French", "French"],
    "rus": ["rus_Cyrl", "Russian", "Russian"],
    "cmn": ["zho_Hans", "Mandarin Chinese", "Chinese (Simplified)"],
    "ltz": ["ltz_Latn", "Luxembourgish", "Luxembourgish"],
    "lav": ["lvs_Latn", "Latvian", "Standard Latvian"],
    "sin": ["sin_Sinh", "Sinhala", "Sinhala"],
    "deu": ["deu_Latn", "German", "German"],
    "hin": ["hin_Deva", "Hindi", "Hindi"],
    "abk": ["", "Abkhaz", ""],  # not in list2
    "kat": ["kat_Geor", "Georgian", "Georgian"],
    "nso": ["nso_Latn", "Northern Sotho", "Northern Sotho"],
    "nya": ["nya_Latn", "Nyanja", "Nyanja"],
    "mar": ["mar_Deva", "Marathi", "Marathi"],
    "hau": ["hau_Latn", "Hausa", "Hausa"]
}


mlsuperb2_to_whisper = {
    "grn": "not_available",
    "yor": "yoruba",
    "mon": "mongolian",
    "azz": "not_available",
    "bos": "bosnian",
    "lga": "not_available",
    "kin": "not_available",
    "msa": "malay",
    "ven": "not_available",
    "ukr": "ukrainian",
    "fil": "tagalog",
    "glg": "galician",
    "cym": "welsh",
    "org_jpn": "japanese",
    "tgk": "tajik",
    "mrj": "not_available",
    "tso": "not_available",
    "tsn": "not_available",
    "tok": "not_available",
    "zul": "not_available",
    "epo": "not_available",
    "afr": "afrikaans",
    "kmr": "not_available",
    "oci": "occitan",
    "ast": "not_available",
    "hye": "armenian",
    "ita": "italian",
    "orm": "not_available",
    "ssw": "not_available",
    "lin": "lingala",
    "som": "somali",
    "dan": "danish",
    "fin": "finnish",
    "nep": "nepali",
    "umb": "not_available",
    "sun": "sundanese",
    "aze": "azerbaijani",
    "luo": "not_available",
    "hrv": "croatian",
    "isl": "icelandic",
    "mlt": "maltese",
    "ory": "not_available",
    "amh": "amharic",
    "fas": "persian",
    "kab": "not_available",
    "snd": "sindhi",
    "tur": "turkish",
    "swe": "swedish",
    "kaz": "kazakh",
    "nob": "norwegian",
    "uig": "not_available",
    "jpn": "japanese",
    "mya": "myanmar",
    "sot": "not_available",
    "nan": "chinese",
    "kor": "korean",
    "slk": "slovak",
    "por": "portuguese",
    "cat": "catalan",
    "yue": "cantonese",
    "wol": "not_available",
    "kan": "kannada",
    "est": "estonian",
    "pus": "pashto",
    "ibo": "not_available",
    "cnh": "not_available",
    "tel": "telugu",
    "hsb": "not_available",
    "kir": "not_available",
    "guj": "gujarati",
    "eng": "english",
    "xty": "not_available",
    "swa": "swahili",
    "mkd": "macedonian",
    "sna": "shona",
    "gle": "not_available",
    "ckb": "not_available",
    "kea": "not_available",
    "tha": "thai",
    "spa": "spanish",
    "khm": "khmer",
    "chv": "not_available",
    "ind": "indonesian",
    "ron": "romanian",
    "hun": "hungarian",
    "jav": "javanese",
    "bul": "bulgarian",
    "ara": "arabic",
    "ina": "not_available",
    "mri": "maori",
    "xho": "not_available",
    "skr": "not_available",
    "kam": "not_available",
    "slv": "slovenian",
    "tat": "tatar",
    "nbl": "not_available",
    "ori": "not_available",
    "ces": "czech",
    "sah": "not_available",
    "lao": "lao",
    "vie": "vietnamese",
    "frr": "not_available",
    "uzb": "uzbek",
    "bel": "belarusian",
    "mhr": "not_available",
    "nno": "nynorsk",
    "ben": "bengali",
    "asm": "assamese",
    "bak": "bashkir",
    "ell": "greek",
    "ceb": "not_available",
    "heb": "hebrew",
    "pan": "punjabi",
    "nor": "norwegian",
    "myv": "not_available",
    "ful": "not_available",
    "div": "not_available",
    "srp": "serbian",
    "tam": "tamil",
    "eus": "basque",
    "nld": "dutch",
    "lit": "lithuanian",
    "urd": "urdu",
    "tos": "not_available",
    "mal": "malayalam",
    "lug": "not_available",
    "pol": "polish",
    "bas": "not_available",
    "bre": "breton",
    "fra": "french",
    "rus": "russian",
    "cmn": "chinese",
    "ltz": "luxembourgish",
    "lav": "latvian",
    "sin": "sinhala",
    "deu": "german",
    "hin": "hindi",
    "abk": "not_available",
    "kat": "georgian",
    "nso": "not_available",
    "nya": "not_available",
    "mar": "marathi",
    "hau": "hausa",
}
